export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS'
export const FILTER_BY_STATUS = 'FILTER_BY_STATUS'
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS'


export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_FILTER = 'SET_FILTER'

export const ADD_STATUS = 'ADD_STATUS'
export const EDIT_STATUS = 'EDIT_STATUS'
export const DELETE_STATUS = 'DELETE_STATUS'